# Copyright 2016 Edward Diener
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false

python: "2.7"

os:
  - linux
  - osx

branches:
  only:
    - master
    - develop

install:
  - cd ..
  - git clone -b $TRAVIS_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init --depth 1 tools/build
  - git submodule update --init --depth 1 libs/config
  - git submodule update --init --depth 1 libs/tokenizer
  - git submodule update --init --depth 1 libs/timer
  - git submodule update --init --depth 1 libs/iterator
  - git submodule update --init --depth 1 libs/lexical_cast
  - git submodule update --init --depth 1 libs/bind
  - git submodule update --init --depth 1 libs/array
  - git submodule update --init --depth 1 libs/container
  - git submodule update --init --depth 1 libs/integer
  - git submodule update --init --depth 1 libs/math
  - git submodule update --init --depth 1 libs/numeric/conversion
  - git submodule update --init --depth 1 libs/range
  - git submodule update --init --depth 1 libs/concept_check
  - git submodule update --init --depth 1 tools/boostdep
  - cp -r $TRAVIS_BUILD_DIR/* libs/function_types
  - python tools/boostdep/depinst/depinst.py function_types
  - ./bootstrap.sh
  - ./b2 headers

script:
  - TOOLSET=gcc,clang
  - if [ $TRAVIS_OS_NAME == osx ]; then TOOLSET=clang; fi
  - ./b2 --verbose-test libs/config/test//config_info toolset=$TOOLSET || true
  - ./b2 libs/function_types/test toolset=$TOOLSET

notifications:
  email:
    on_success: always
